Wek queue service
minova-afis/aero.minova.cas pull request #295
Opened 2022-04-27 12:02 UTC by weber-minova

2022-04-28 09:08 UTC, splitcells requested changes

2022-04-28 09:08 UTC, splitcells commented on service/src/main/java/aero/minova/cas/service/QueueService.java
> +	private void saveMessage(String message, String procedureName, String serviceName) {
Hier müsste man entsprechend als Argumente message und topic haben.
Die SQL-Prozedur würde dann entsprechende für jeden Dienst des Topics einen Eintrag in die messages-Tabelle machen.

2022-04-28 09:08 UTC, splitcells commented on servicenotifier/src/main/java/aero/minova/cas/servicenotifier/ServiceNotifierService.java
> +@Service
Bitte `@Deprecated` verwenden.

2022-04-28 12:55 UTC, weber-minova commented on service/src/main/java/aero/minova/cas/service/QueueService.java
> +				increaseAttempts(pendingMessage);
> Das muss man, glaube ich, nur im Fehlerfall machen.

Aber dann steht in der Datenbank, wenn eine Nachricht erfolgreich versandt wurde NumberOfAttempts =  0

2022-04-29 06:40 UTC, weber-minova commented on service/src/main/java/aero/minova/cas/service/QueueService.java
> +						|| pendingMessage.getValues().get(7).getIntegerValue() >= allowedNumberOfAttempts) {
> Diese Nachrichten bitte nicht löschen, sonst wird es beim Support schwieriger sein eventuelle Fehler zu finde: `pendingMessage.getValues().get(7).getIntegerValue() >= allowedNumberOfAttempts`

Sie werden nur auf -1 gesetzt. Ist das trotzdem ein Problem?

2022-05-02 07:36 UTC, splitcells requested changes

2022-05-02 07:36 UTC, splitcells commented on CHANGELOG.adoc
> +Automatisches Speichern, Queueing und Versenden von Nachrichten an andere Dienste.
Grammar-Nazi: `.` -> `implementieren.` und man hat einen Satz.

2022-05-02 07:36 UTC, splitcells commented on service/src/main/java/aero/minova/cas/service/QueueService.java
> +			Map<String, BiFunction<Table, ResponseEntity<Object>, String>> applyableFunctions = serviceMessageCreators.get(t.getName());
Eher sowas wie topicSpecificMessages.

2022-05-02 07:36 UTC, splitcells commented on service/src/main/java/aero/minova/cas/service/QueueService.java
> +	 * Speichert eine Nachricht für einen Service.
-> Speicher eine Nachricht für einen Topic.

2022-05-02 07:36 UTC, splitcells commented on service/src/main/java/aero/minova/cas/service/QueueService.java
> +				logger.logQueueService("Saving message '" + message + "'");
-> `Saving message for topic <topic> because of <procedureName>: + '<message>'`

2022-05-02 07:36 UTC, splitcells commented on service/src/main/resources/logback-spring.xml
> -		<appender-ref ref="console"/>
👍

2022-05-02 07:36 UTC, splitcells commented on servicenotifier/src/main/java/aero/minova/cas/servicenotifier/ServiceNotifierService.java
> -/*
Den Kommentar musste man eigentlich nicht löschen, aber ok.

2022-05-02 08:18 UTC, splitcells approved these changes

2022-05-02 08:18 UTC, splitcells commented on app/src/main/app/sql/xpcasDeleteServiceMessage.sql
> +where MessageCreationDate < dateadd(day,-30,getDate());
` MessageCreationDate < getDate() - 30` geht auch.

2022-05-02 08:18 UTC, splitcells commented on service/src/main/java/aero/minova/cas/service/QueueService.java
> +					safeAsSent(true, pendingMessage);
Gute Umsetzung

2022-05-02 08:18 UTC, merged