Kein Commit zwischen XProcedures und Extensions auch beim unsicheren Ausführen
minova-afis/aero.minova.cas pull request #342
Opened 2022-07-19 10:37 UTC by weber-minova

closes #341

2022-07-20 13:58 UTC, splitcells requested changes

2022-07-20 13:58 UTC, splitcells commented on service/src/main/java/aero/minova/cas/controller/SqlProcedureController.java
> +	private ResponseEntity checkForExtension(Table inputTable) {
Als Rückgabewert bitte Optional verwenden.

2022-07-20 13:58 UTC, splitcells commented on service/src/main/java/aero/minova/cas/controller/SqlProcedureController.java
> +			synchronized (extensionSynchronizer) {
Am besten containsKey mit synchronisieren, falls in Zukunft-Extensions schon beim Start vom CAS ausgeführt werden.

2022-07-20 13:58 UTC, splitcells commented on service/src/main/java/aero/minova/cas/controller/XSqlProcedureController.java
> +			resultSets = processXProcedures(inputTables, resultSets, sb, connection);
Bitte Bugfix in der Changelog dokumentieren.

2022-07-20 13:58 UTC, splitcells commented on service/src/main/java/aero/minova/cas/controller/SqlProcedureController.java
> +	public ResponseEntity processSqlProcedureRequest(Table inputTable, List<Row> privilegeRequest) throws Exception {
Bitte alte Methoden erstmal nicht ändern.
Wir wollen die Rückwärtskompatibilität erstmal nicht brechen und sollten uns das auch aufgrund von Plugins abgewöhnen.
Lasse die processSqlProcedureRequest und calculateSqlProcedureRequest so wie sie ist:
Ohne Extensionausführung und mit alten Rückgabe werte.

Erstelle stattdessen eine processProcedureRequest, die das gewünschte durchführt.

2022-07-20 13:58 UTC, splitcells commented on service/src/main/java/aero/minova/cas/controller/SqlProcedureController.java
> +	public ResponseEntity unsecurelyProcessProcedure(Table inputTable) throws Exception {
Auch hier die Rückwärtskompatibilität erstmal nicht brechen.
Deprecate diese erstmal.

2022-07-22 14:07 UTC, splitcells requested changes

2022-07-22 14:07 UTC, splitcells commented on service/src/main/java/aero/minova/cas/controller/SqlProcedureController.java
> +		ResponseEntity extensionResult = checkForExtension(inputTable).orElse(null);
```
Optional<ResponseEntity> extensionResult = checkForExtension(inputTable);
if (extensionResult.isPresent()) {
    [...]
}
```

2022-07-22 14:07 UTC, splitcells commented on service/src/main/java/aero/minova/cas/controller/SqlProcedureController.java
> +			throws SQLException, ProcedureException {
Bitte API nicht ändern.

2022-07-22 14:14 UTC, weber-minova commented on service/src/main/java/aero/minova/cas/controller/SqlProcedureController.java
> +			throws SQLException, ProcedureException {
This, I forgot

2022-07-27 15:53 UTC, splitcells requested changes

2022-07-27 15:53 UTC, splitcells commented on service/src/main/java/aero/minova/cas/controller/SqlProcedureController.java
> +	public ResponseEntity<?> unsecurelyProcessProcedureWithExtensionCheck(Table inputTable) throws Exception {
Wie wäre es mit unsecurelyExecuteProcedure in Anlehnung an executeProcedure,
welche die selbe Funktion haben soll, wenn man vom Rechtesystem absieht.

Damit wäre es auch kürzer.

2022-08-04 09:27 UTC, weber-minova commented on service/src/main/java/aero/minova/cas/controller/SqlProcedureController.java
> +	Optional<ResponseEntity> checkForExtension(Table inputTable) {
Methode wird im XSqlProcedureController benötigt

2022-08-16 08:53 UTC, merged