Abschneiden von Daten beim Setup erlauben
minova-afis/aero.minova.cas pull request #580
Opened 2023-06-01 10:47 UTC by Bauer-David

2023-06-01 11:11 UTC, weber-minova requested changes
So ist das Problem noch nicht komplett gelöst.
In Zeile 186 des ursprünglichen Codes, werden noch die Values der Tabellen gefüllt. Dort wird potentiell auch der LastUser genommen werden.

2023-06-01 11:11 UTC, weber-minova commented on setup/src/main/java/aero/minova/cas/setup/InstallToolIntegration.java
> +			// ANSI_WARNINGS OFF ignoriert Warnung bei zu langen Datensätzen und schenidet stattdessen diese direkt ab.
schenidet -> schneidet

2023-06-01 12:03 UTC, Bauer-David commented
> So ist das Problem noch nicht komplett gelöst.
> In Zeile 186 des ursprünglichen Codes, werden noch die Values der Tabellen gefüllt. Dort wird potentiell auch der LastUser genommen werden.

in welchem ursprüngliche Code Zeil 186?

2023-06-01 12:07 UTC, weber-minova commented
> > So ist das Problem noch nicht komplett gelöst.
> > In Zeile 186 des ursprünglichen Codes, werden noch die Values der Tabellen gefüllt. Dort wird potentiell auch der LastUser genommen werden.
> 
> in welchem ursprüngliche Code Zeil 186?

Aaah, ich hab mich in der Klasse vertan. Hatte mir die readoutSchema-Methode angeschaut.

2023-06-01 12:08 UTC, merged

2023-06-12 10:42 UTC, martins-1992 commented
Bin von der Lösung nicht so angetan,
da somit bei anderen Fehlern dieser Fehler jetzt auch geschluckt wird.

2023-06-13 07:37 UTC, Bauer-David commented
> Bin von der Lösung nicht so angetan,
> da somit bei anderen Feldern dieser Fehler jetzt auch geschluckt wird.

Gegenvorschlag?

2023-06-14 08:15 UTC, martins-1992 commented
Felder länger gestalten.