indirekte third party dependencies werden nach Setup durchsucht
minova-afis/aero.minova.cas pull request #617
Opened 2023-06-21 12:14 UTC by wis36

Beim Versuch, ein lokales CAS aufzusetzen (https://github.com/minova-afis/aero.minova.workingtime/issues/29) ist mir aufgefallen, dass teilweise die third party dependencies nach Setup.xml durchsucht werden. Das schlägt natürlich fehl und das Setup funktioniert nicht.

Ich habe herausgefunden, dass es sich um indirekte Abhängigkeiten handelt. Das war bei der bisherigen Implementierung noch nicht berücksichtigt.

2023-06-21 13:03 UTC, scholz-afis requested changes

2023-06-21 13:36 UTC, wis36 commented on setup/src/main/java/aero/minova/cas/setup/dependency/DependencyOrder.java
> +
Hatte ich zuvor so gemacht, ist allerdings mMn komplizierter, eine 2-stufige Struktur zu bearbeiten, die danach in eine einfache Liste konvertiert wird. Deshalb habe ich der Einfachheit halber lieber die flache Liste bearbeitet.

2023-06-21 13:37 UTC, wis36 commented on setup/src/main/java/aero/minova/cas/setup/dependency/DependencyOrder.java
>  	private static boolean isThirdPartyDependency(String dependency) {
Siehe oben, um den Prozess zu vereinfachen. Ich weiß nicht ob die benötigte Rechenzeit hier relevant ist, die du oben erwähnt hattest.

2023-06-22 07:21 UTC, scholz-afis commented on setup/src/main/java/aero/minova/cas/setup/dependency/DependencyOrder.java
>  	private static boolean isThirdPartyDependency(String dependency) {
@wis36 Ja, aus meiner Sicht ist Sie das, sonst hätte ich das Aussortieren der Dependencies ja nicht nach oben gezogen. Auch ich möchte nicht mehr Code als nötig schreiben. Das Traversieren von Graphen ist aufwendiger (Rechenleistung) als das Traversieren von einfachen Bäumen.

Allerdings bin ich nicht Maintainer:in des Projekts und treffe keine finale Entscheidung über das Approval. Ich habe mir Deine Änderungen angeschaut, weil Du mich als "Reviewer" eingetragen hast.

2023-06-26 06:02 UTC, wis36 commented on setup/src/main/java/aero/minova/cas/setup/dependency/DependencyOrder.java
>  	private static boolean isThirdPartyDependency(String dependency) {
"ob die benötigte Rechenzeit hier relevant ist" habe ich so gemeint:
Diese Codestelle wird nur einmal bei der Installation eines Systems aufgerufen. Da kommt es auf 0,3 Sekunden mehr oder weniger nicht an.

2023-06-28 08:19 UTC, scholz-afis approved these changes

2023-07-06 12:48 UTC, merged