Wek #656 logger für allgemeine infos
minova-afis/aero.minova.cas pull request #706
Opened 2023-08-28 12:41 UTC by weber-minova

2023-09-01 12:37 UTC, martins-1992 requested changes

2023-09-01 12:37 UTC, martins-1992 commented on service/src/main/java/aero/minova/cas/CustomLogger.java
> +	private static final Logger LOGGER = LoggerFactory.getLogger("SqlLogger");
Bitte im Changelog angeben, dass die Kompatibilität gebrochen wird,
indem die CustomLogger-Logger auf private gesetzt werden.

2023-09-01 12:40 UTC, weber-minova commented on service/src/main/java/aero/minova/cas/CustomLogger.java
> +	private static final Logger LOGGER = LoggerFactory.getLogger("SqlLogger");
> Bitte im Changelog angeben, dass die Kompatibilität gebrochen wird, indem die CustomLogger-Logger auf private gesetzt werden.

Dazu würde ich auch gerne deine Meinung wissen, ob es okay ist, alle Logger auf private zu setzen. : )

2023-09-04 11:22 UTC, martins-1992 requested changes

2023-09-04 11:22 UTC, martins-1992 commented on service/src/main/java/aero/minova/cas/CustomLogger.java
> +	private static final Logger LOGGER = LoggerFactory.getLogger("SqlLogger");
Wenn es keinen gesonderten Grund hat, würde ich es nicht ändern, da es Mehraufwand aufgrund von wahrscheinlich kaputten Modulen bedeutet.
Wenn es aber Gründe hat, könnte man es mal ändern,
aber vorläufig danach nie wieder.

Wenn der Grund nur lautet, dass es hübscher aussieht, wäre ich eher dagegen.

2023-09-07 16:43 UTC, martins-1992 commented
@weber-minova Sorry für die Planänderung: Bitte die Kompatibilität nicht brechen.
Also, die `public Logger`-Felder so lassen.
Ich werde Kompatibilität wahrscheinlich für was brauchen.

2023-09-08 06:41 UTC, weber-minova commented
> @weber-minova Sorry für die Planänderung: Bitte die Kompatibilität nicht brechen. Also, die `public Logger`-Felder so lassen. Ich werde Kompatibilität wahrscheinlich für was brauchen.

NP NP

2023-09-08 09:39 UTC, martins-1992 requested changes

2023-09-08 09:39 UTC, martins-1992 commented on service/src/main/java/aero/minova/cas/CustomLogger.java
> +	public static final Logger PRIVILEGELOGGER = LoggerFactory.getLogger("PrivilegeLogger");
Bitte die Namen nicht ändern und kein static final verwenden,
damit die Kompatibilität nicht gebrochen wird.

2023-09-11 07:28 UTC, martins-1992 requested changes

2023-09-11 07:28 UTC, martins-1992 commented on service/src/main/java/aero/minova/cas/CustomLogger.java
> +	public Logger logger = LoggerFactory.getLogger("SqlLogger");
Das `static final` fehlt noch und die Großschreibung soll gleich bleiben.

2023-09-11 07:55 UTC, weber-minova commented on service/src/main/java/aero/minova/cas/CustomLogger.java
> +	public Logger logger = LoggerFactory.getLogger("SqlLogger");
Aber ich dachte, ich soll das rückgängig machen? :(

2023-09-11 07:58 UTC, martins-1992 approved these changes

2023-09-11 07:58 UTC, merged