Wek mehr tests
minova-afis/aero.minova.cas pull request #805
Opened 2023-11-24 10:34 UTC by weber-minova

closes #406
closes #469 
closes #722 
closes #556

2023-11-24 13:47 UTC, martins-1992 commented
![grafik](https://github.com/minova-afis/aero.minova.cas/assets/7956931/d0162001-93db-4878-8a29-93e2c7117361)

2024-01-05 14:39 UTC, weber-minova commented
Yay! Mind. 30% Codeabdeckung! 
<img width="1416" alt="Bildschirmfoto 2024-01-05 um 15 36 22" src="https://github.com/minova-afis/aero.minova.cas/assets/75690564/fc8c4347-9fc6-4a12-9b83-6df50a263ddb">

![honest-work-meme-cb0f0fb2227fb84b77b3c9a851ac09b095ab74d8-s1100-c50](https://github.com/minova-afis/aero.minova.cas/assets/75690564/1c6b3519-c071-4ea5-851e-95022d8ff3eb)

2024-01-18 11:48 UTC, martins-1992 requested changes
Alles falsch

2024-01-19 08:51 UTC, martins-1992 requested changes

2024-01-19 08:51 UTC, martins-1992 commented on service/src/main/java/aero/minova/cas/service/ProcedureService.java
> +					// ausgeführt wurde.
Was bedeutet "No Data available"?
Ist das ein Fehler?
Wenn ja, sollte man nicht `resultForThisRow.setReturnCode(reCode);` auf 1 setzen?

2024-01-19 08:51 UTC, martins-1992 commented on service/src/main/java/aero/minova/cas/servicenotifier/ServiceNotifierRegistrationAPI.java
> +		} catch (Exception e) {
Warum wird die Exception gefangen?

2024-01-19 08:51 UTC, martins-1992 commented on service/src/test/java/aero/minova/cas/controller/SQLProcedureControllerTest.java
> +		authorizationService.findOrCreateUserPrivilege(SECURITYVIEW);
Würde es nicht reichen, den Nutzer und SECURITYVIEW zu setzen?
Bspw. über ´@BeforeAll´.

2024-01-19 08:51 UTC, martins-1992 commented on service/src/test/java/aero/minova/cas/service/QueueServiceTest.java
> +		assertEquals(1, serviceRepo.findAll().size());
Hier sollte man den Inhalt und nicht nur deren Größe prüfen.

2024-01-19 09:32 UTC, weber-minova commented on service/src/main/java/aero/minova/cas/servicenotifier/ServiceNotifierRegistrationAPI.java
> +		} catch (Exception e) {
Weil sonst das gesamte CAS nicht startet, nur weil ein Service nicht registriert werden konnte.

2024-01-19 10:01 UTC, weber-minova commented on service/src/main/java/aero/minova/cas/service/ProcedureService.java
> +					// ausgeführt wurde.
Kommentar geupdatet

2024-02-06 10:30 UTC, martins-1992 commented on service/src/main/java/aero/minova/cas/servicenotifier/ServiceNotifierRegistrationAPI.java
> +		} catch (Exception e) {
Aber die Konfiguration vom CAS ist dann kaputt und wird einen entsprechenden Supportfall später verursachen.

2024-02-06 10:35 UTC, martins-1992 requested changes
Einzig die Fehlerbehandlung bei der Dienst-Registrierung finde ich zweifelhaft.

2024-03-12 13:13 UTC, weber-minova commented
> Einzig die Fehlerbehandlung bei der Dienst-Registrierung finde ich zweifelhaft.

Es wird jetzt, statt nur zu loggen, eine Exception geworfen.

2024-03-13 05:56 UTC, martins-1992 requested changes

2024-03-13 05:56 UTC, martins-1992 commented on service/src/test/java/aero/minova/cas/service/QueueServiceTest.java
> +		assertEquals("Service", serviceRepo.findByKeyLong(1).get().getKeyText());
Hier könnte man folgendes in eine Variable auslagern,
um die Asserts übersichtlicher zu gestalten:
````
assertEquals("Service", serviceRepo.findByKeyLong(1).get().getKeyText());
assertEquals("test", serviceRepo.findByKeyLong(1).get().getUsername());
assertEquals("abc1234", serviceRepo.findByKeyLong(1).get().getPassword());
assertEquals(0, serviceRepo.findByKeyLong(1).get().getPort());
assertEquals("localhost", serviceRepo.findByKeyLong(1).get().getServiceUrl());
````
 -> 
````
final var testService = serviceRepo.findByKeyLong(1).get();

assertEquals("Service", testService.getKeyText());
assertEquals("test", testService.getUsername());
assertEquals("abc1234", testService.getPassword());
assertEquals(0, testService.getPort());
assertEquals("localhost", testService.getServiceUrl());
````

Dadurch erreicht man auch eine gewisse Gliederung,
wodurch man einfacher erkennen kann,
dass in einem Block eine Sache getestet wird.

2024-04-30 10:29 UTC, merged