PreparedStatements und ResultSets nach der Ausführung schließen
minova-afis/aero.minova.cas pull request #826
Opened 2023-12-07 10:47 UTC by weber-minova

2023-12-08 11:00 UTC, martins-1992 requested changes

2023-12-08 11:00 UTC, martins-1992 commented on service/src/main/java/aero/minova/cas/service/ViewService.java
> +			} finally {
Hier bitte das try nur für das preparedStatement anstatt preparedViewStatement verwenden.

2024-01-08 09:10 UTC, martins-1992 approved these changes

2024-01-08 09:11 UTC, martins-1992 commented
Anscheinend gibt es jetzt Konflikte zum main-Branch.

2024-01-08 09:13 UTC, weber-minova commented
> Anscheinend gibt es jetzt Konflikte zum main-Branch.

?
Siiiicher?

2024-01-08 09:16 UTC, martins-1992 commented
![grafik](https://github.com/minova-afis/aero.minova.cas/assets/7956931/fba4d82d-1f2d-4ab1-98cf-67c9739ded0f)

![grafik](https://github.com/minova-afis/aero.minova.cas/assets/7956931/2d7d9274-dc49-4a13-8c8c-170fbee4a4a1)

2024-01-08 09:17 UTC, weber-minova commented
> ![grafik](https://private-user-images.githubusercontent.com/7956931/294854696-fba4d82d-1f2d-4ab1-98cf-67c9739ded0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU3MDMsIm5iZiI6MTcwNDcwNTQwMywicGF0aCI6Ii83OTU2OTMxLzI5NDg1NDY5Ni1mYmE0ZDgyZC0xZjJkLTRhYjEtOThjZi02N2M5NzM5ZGVkMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDkxNjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVjZTFiMWUzMDAxM2M1NzFkYjVhYjk4MmYyMDg3ZjVlM2ZkZWQ4MGVmZDQ0ODI0MzRjYjk0NzE1NTNlOThlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TpHLC79WXTQ2As7CETxrTb8bCxJx9bAu8quGU-zEXTE)
> 
> ![grafik](https://private-user-images.githubusercontent.com/7956931/294854822-2d7d9274-dc49-4a13-8c8c-170fbee4a4a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU3MDMsIm5iZiI6MTcwNDcwNTQwMywicGF0aCI6Ii83OTU2OTMxLzI5NDg1NDgyMi0yZDdkOTI3NC1kYzQ5LTRhMTMtOGM4Yy0xNzBmYmVlNGE0YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDkxNjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M4ZGNhN2NiODBhMTRkZTM3MjAxMDEwZWJjYTdkYTM5MjE0ZDE3OGFjMjUyMDhlZjFhYWY4YmIzMzdiOTJiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WHe14Sh08midGEIq1bTQxq2xEyAyAsf2ztiExCKwMIY)

<img width="1024" alt="Bildschirmfoto 2024-01-08 um 10 16 55" src="https://github.com/minova-afis/aero.minova.cas/assets/75690564/c29105a1-1547-42b9-871a-cfa9fa3c054e">

Wie geht das? xD

2024-01-08 09:30 UTC, martins-1992 commented
K, dann kannst du den Code ja mergen. Have fun

2024-01-08 09:44 UTC, weber-minova commented
> K, dann kannst du den Code ja mergen. Have fun

Okidoki, mach ich :D

2024-01-08 09:44 UTC, merged