Wek cas i18n
minova-afis/aero.minova.cas pull request #869
Opened 2024-02-02 08:19 UTC by weber-minova

2024-02-06 12:09 UTC, martins-1992 requested changes

2024-02-07 10:01 UTC, weber-minova commented on resource-plugin/src/main/java/aero/minova/cas/resource/maven/plugin/ResourceListGenerator.java
> +					try (Stream<String> stream = Files.lines(r, StandardCharsets.ISO_8859_1)) {
> Warum nicht UTF-8?

Die russische Übersetzung kann mit UTF-8 nicht umgehen und benötigt leider ISO_8859_1.

2024-02-07 10:31 UTC, martins-1992 commented on resource-plugin/src/main/java/aero/minova/cas/resource/maven/plugin/ResourceListGenerator.java
> +					try (Stream<String> stream = Files.lines(r, StandardCharsets.ISO_8859_1)) {
Wie hat sich das gezeigt? Das sollten wir zusammen durchgehen.

2024-02-09 08:20 UTC, weber-minova commented on resource-plugin/src/main/java/aero/minova/cas/resource/maven/plugin/ResourceListGenerator.java
> +					try (Stream<String> stream = Files.lines(r, StandardCharsets.ISO_8859_1)) {
Wenn man versucht mit UTF-8 das customer-build-project zu bauen, kommt die Fehlermeldung:
`Failed to execute goal [32maero.minova:cas.resource.maven.plugin:13.1.3-SNAPSHOT:generate-resource-file[m [1m(generate-resource-file)[m on project [36mcas-customer-build-project[m: [1;31mExecution generate-resource-file of goal aero.minova:cas.resource.maven.plugin:13.1.3-SNAPSHOT:generate-resource-file failed: java.lang.RuntimeException: java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1[m -> [1m[Help 1]`

Was eben falsches CharSet bzw falsches Enconding bedeutet: https://stackoverflow.com/questions/30609062/java-nio-charset-malformedinputexception-input-length-1

2024-02-12 08:38 UTC, martins-1992 approved these changes

2024-02-12 08:49 UTC, merged