Wek cas version auslesen
minova-afis/aero.minova.cas pull request #959
Opened 2024-04-05 09:23 UTC by weber-minova

2024-04-08 09:05 UTC, weber-minova commented
Im Postman sieht die Anfrage mit Ergebnis so aus:
<img width="1075" alt="Bildschirmfoto 2024-04-08 um 11 04 39" src="https://github.com/minova-afis/aero.minova.cas/assets/75690564/897b358f-8277-4aff-9f80-039a3196afad">

In der CAS Console sieht es so aus:
<img width="1543" alt="Bildschirmfoto 2024-04-05 um 11 06 56" src="https://github.com/minova-afis/aero.minova.cas/assets/75690564/ebe97c86-8d39-4dd4-a667-efda9d4b75c4">

2024-05-23 09:04 UTC, martins-1992 requested changes

2024-05-23 09:04 UTC, martins-1992 commented on service/src/main/java/aero/minova/cas/CustomLogger.java
> +		String user = SecurityContextHolder.getContext().getAuthentication() != null ? SecurityContextHolder.getContext().getAuthentication().getName() : "CAS";
Würde  als Benutzernamen sowas wie anonymous bevorzugen,
um zu signalieren, dass kein authentifizierte Benutzer vorhanden ist.

2024-05-23 09:04 UTC, martins-1992 commented on service/src/main/java/aero/minova/cas/controller/CommunicationController.java
> +	public ResponseEntity<String> getVersion() throws IOException {
Ich würde ein JSON wie `{ "groupId" [...], "artefactId" [...], "majorVersion" [...], "minorVersion" [...], "patchVersion" [...], "Versionqualifier" [...]}` bevorzugen.
Dann ist keine String-Parse-Logik im Client notwendig.

2024-08-08 08:17 UTC, janiak-minova commented
Neue Ausgabe im Postman:

<img width="627" alt="Bildschirmfoto 2024-08-08 um 10 16 11" src="https://github.com/user-attachments/assets/a828a448-69fa-48a0-8f68-bea9af5ee38a">

2024-08-08 08:30 UTC, merged